services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: directory
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d directory" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
volumes:
  pg_data: